### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by Isiaka399** [qiskit-community/qiskit-research#116]
I am trying to import Peptide from qiskit_research by using this code:

from qiskit_research.protein_folding.peptide.pepetide import *

But I am getting this error:

No module named qiskit_research.protein_folding

I will appreciate if someone can explain why I am getting this error

**Comment by kevinsung** [comment]
The protein folding module is no longer part of Qiskit Research. It has been moved to https://github.com/qiskit-community/quantum-protein-folding.
